### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/GetOptions#1]
## To-do list
- [x] camelCased properties for returned `.options` (done in 2691b5c)
- [x] Cater to options passed from command-line as `--option=value` (done in d47b5c5)
- [x] Add option to toggle duplication of alternate option names (done in 8ac25ac)
- [x] Support for clustered short-options (e.g., `-m3 -xvfz`, etc) (done in c97cc35)
- [x] Add a setting to control how repeated options are handled (done in 25b5265)
- [x] Package this shit up as an NPM module (done in 55f96b1)
